# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poilog2 <- function(x, y, my1, my2, sig1, sig2, ro, nrN) {
    .Call('_poilogcpp_poilog2', PACKAGE = 'poilogcpp', x, y, my1, my2, sig1, sig2, ro, nrN)
}

poilog1 <- function(x, my, sig, nrN) {
    .Call('_poilogcpp_poilog1', PACKAGE = 'poilogcpp', x, my, sig, nrN)
}

